/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as RecuperarRouteImport } from './routes/recuperar'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin/configuracoes'
import { Route as AdminCreditosRouteImport } from './routes/admin/creditos'
import { Route as AdminDenunciasRouteImport } from './routes/admin/denuncias'
import { Route as AdminFilaRouteImport } from './routes/admin/fila'
import { Route as AdminUsuariosRouteImport } from './routes/admin/usuarios'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAjudarRouteImport } from './routes/app/ajudar'
import { Route as AppContaRouteImport } from './routes/app/conta'
import { Route as AppConvidarRouteImport } from './routes/app/convidar'
import { Route as AppCreditosRouteImport } from './routes/app/creditos'
import { Route as AppDenunciarRouteImport } from './routes/app/denunciar'
import { Route as AppFilaRouteImport } from './routes/app/fila'
import { Route as AppHistoricoRouteImport } from './routes/app/historico'
import { Route as AppLinkRouteImport } from './routes/app/link'
import { Route as AppRankingRouteImport } from './routes/app/ranking'
import { Route as AppRegrasRouteImport } from './routes/app/regras'
import { Route as AppSuporteRouteImport } from './routes/app/suporte'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarRoute = RecuperarRouteImport.update({
  id: '/recuperar',
  path: '/recuperar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCreditosRoute = AdminCreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDenunciasRoute = AdminDenunciasRouteImport.update({
  id: '/denuncias',
  path: '/denuncias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFilaRoute = AdminFilaRouteImport.update({
  id: '/fila',
  path: '/fila',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAjudarRoute = AppAjudarRouteImport.update({
  id: '/ajudar',
  path: '/ajudar',
  getParentRoute: () => AppRoute,
} as any)
const AppContaRoute = AppContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AppRoute,
} as any)
const AppConvidarRoute = AppConvidarRouteImport.update({
  id: '/convidar',
  path: '/convidar',
  getParentRoute: () => AppRoute,
} as any)
const AppCreditosRoute = AppCreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => AppRoute,
} as any)
const AppDenunciarRoute = AppDenunciarRouteImport.update({
  id: '/denunciar',
  path: '/denunciar',
  getParentRoute: () => AppRoute,
} as any)
const AppFilaRoute = AppFilaRouteImport.update({
  id: '/fila',
  path: '/fila',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoricoRoute = AppHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AppRoute,
} as any)
const AppLinkRoute = AppLinkRouteImport.update({
  id: '/link',
  path: '/link',
  getParentRoute: () => AppRoute,
} as any)
const AppRankingRoute = AppRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AppRoute,
} as any)
const AppRegrasRoute = AppRegrasRouteImport.update({
  id: '/regras',
  path: '/regras',
  getParentRoute: () => AppRoute,
} as any)
const AppSuporteRoute = AppSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/recuperar': typeof RecuperarRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/creditos': typeof AdminCreditosRoute
  '/admin/denuncias': typeof AdminDenunciasRoute
  '/admin/fila': typeof AdminFilaRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/app/ajudar': typeof AppAjudarRoute
  '/app/conta': typeof AppContaRoute
  '/app/convidar': typeof AppConvidarRoute
  '/app/creditos': typeof AppCreditosRoute
  '/app/denunciar': typeof AppDenunciarRoute
  '/app/fila': typeof AppFilaRoute
  '/app/historico': typeof AppHistoricoRoute
  '/app/link': typeof AppLinkRoute
  '/app/ranking': typeof AppRankingRoute
  '/app/regras': typeof AppRegrasRoute
  '/app/suporte': typeof AppSuporteRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/recuperar': typeof RecuperarRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/creditos': typeof AdminCreditosRoute
  '/admin/denuncias': typeof AdminDenunciasRoute
  '/admin/fila': typeof AdminFilaRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/app/ajudar': typeof AppAjudarRoute
  '/app/conta': typeof AppContaRoute
  '/app/convidar': typeof AppConvidarRoute
  '/app/creditos': typeof AppCreditosRoute
  '/app/denunciar': typeof AppDenunciarRoute
  '/app/fila': typeof AppFilaRoute
  '/app/historico': typeof AppHistoricoRoute
  '/app/link': typeof AppLinkRoute
  '/app/ranking': typeof AppRankingRoute
  '/app/regras': typeof AppRegrasRoute
  '/app/suporte': typeof AppSuporteRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/recuperar': typeof RecuperarRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/creditos': typeof AdminCreditosRoute
  '/admin/denuncias': typeof AdminDenunciasRoute
  '/admin/fila': typeof AdminFilaRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/app/ajudar': typeof AppAjudarRoute
  '/app/conta': typeof AppContaRoute
  '/app/convidar': typeof AppConvidarRoute
  '/app/creditos': typeof AppCreditosRoute
  '/app/denunciar': typeof AppDenunciarRoute
  '/app/fila': typeof AppFilaRoute
  '/app/historico': typeof AppHistoricoRoute
  '/app/link': typeof AppLinkRoute
  '/app/ranking': typeof AppRankingRoute
  '/app/regras': typeof AppRegrasRoute
  '/app/suporte': typeof AppSuporteRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/cadastro'
    | '/login'
    | '/onboarding'
    | '/recuperar'
    | '/admin/configuracoes'
    | '/admin/creditos'
    | '/admin/denuncias'
    | '/admin/fila'
    | '/admin/usuarios'
    | '/app/ajudar'
    | '/app/conta'
    | '/app/convidar'
    | '/app/creditos'
    | '/app/denunciar'
    | '/app/fila'
    | '/app/historico'
    | '/app/link'
    | '/app/ranking'
    | '/app/regras'
    | '/app/suporte'
    | '/admin/'
    | '/app/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/onboarding'
    | '/recuperar'
    | '/admin/configuracoes'
    | '/admin/creditos'
    | '/admin/denuncias'
    | '/admin/fila'
    | '/admin/usuarios'
    | '/app/ajudar'
    | '/app/conta'
    | '/app/convidar'
    | '/app/creditos'
    | '/app/denunciar'
    | '/app/fila'
    | '/app/historico'
    | '/app/link'
    | '/app/ranking'
    | '/app/regras'
    | '/app/suporte'
    | '/admin'
    | '/app'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/cadastro'
    | '/login'
    | '/onboarding'
    | '/recuperar'
    | '/admin/configuracoes'
    | '/admin/creditos'
    | '/admin/denuncias'
    | '/admin/fila'
    | '/admin/usuarios'
    | '/app/ajudar'
    | '/app/conta'
    | '/app/convidar'
    | '/app/creditos'
    | '/app/denunciar'
    | '/app/fila'
    | '/app/historico'
    | '/app/link'
    | '/app/ranking'
    | '/app/regras'
    | '/app/suporte'
    | '/admin/'
    | '/app/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RecuperarRoute: typeof RecuperarRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar': {
      id: '/recuperar'
      path: '/recuperar'
      fullPath: '/recuperar'
      preLoaderRoute: typeof RecuperarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/creditos': {
      id: '/admin/creditos'
      path: '/creditos'
      fullPath: '/admin/creditos'
      preLoaderRoute: typeof AdminCreditosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/denuncias': {
      id: '/admin/denuncias'
      path: '/denuncias'
      fullPath: '/admin/denuncias'
      preLoaderRoute: typeof AdminDenunciasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fila': {
      id: '/admin/fila'
      path: '/fila'
      fullPath: '/admin/fila'
      preLoaderRoute: typeof AdminFilaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ajudar': {
      id: '/app/ajudar'
      path: '/ajudar'
      fullPath: '/app/ajudar'
      preLoaderRoute: typeof AppAjudarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/conta': {
      id: '/app/conta'
      path: '/conta'
      fullPath: '/app/conta'
      preLoaderRoute: typeof AppContaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/convidar': {
      id: '/app/convidar'
      path: '/convidar'
      fullPath: '/app/convidar'
      preLoaderRoute: typeof AppConvidarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/creditos': {
      id: '/app/creditos'
      path: '/creditos'
      fullPath: '/app/creditos'
      preLoaderRoute: typeof AppCreditosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/denunciar': {
      id: '/app/denunciar'
      path: '/denunciar'
      fullPath: '/app/denunciar'
      preLoaderRoute: typeof AppDenunciarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fila': {
      id: '/app/fila'
      path: '/fila'
      fullPath: '/app/fila'
      preLoaderRoute: typeof AppFilaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/historico': {
      id: '/app/historico'
      path: '/historico'
      fullPath: '/app/historico'
      preLoaderRoute: typeof AppHistoricoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/link': {
      id: '/app/link'
      path: '/link'
      fullPath: '/app/link'
      preLoaderRoute: typeof AppLinkRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ranking': {
      id: '/app/ranking'
      path: '/ranking'
      fullPath: '/app/ranking'
      preLoaderRoute: typeof AppRankingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/regras': {
      id: '/app/regras'
      path: '/regras'
      fullPath: '/app/regras'
      preLoaderRoute: typeof AppRegrasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suporte': {
      id: '/app/suporte'
      path: '/suporte'
      fullPath: '/app/suporte'
      preLoaderRoute: typeof AppSuporteRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminCreditosRoute: typeof AdminCreditosRoute
  AdminDenunciasRoute: typeof AdminDenunciasRoute
  AdminFilaRoute: typeof AdminFilaRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminCreditosRoute: AdminCreditosRoute,
  AdminDenunciasRoute: AdminDenunciasRoute,
  AdminFilaRoute: AdminFilaRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppAjudarRoute: typeof AppAjudarRoute
  AppContaRoute: typeof AppContaRoute
  AppConvidarRoute: typeof AppConvidarRoute
  AppCreditosRoute: typeof AppCreditosRoute
  AppDenunciarRoute: typeof AppDenunciarRoute
  AppFilaRoute: typeof AppFilaRoute
  AppHistoricoRoute: typeof AppHistoricoRoute
  AppLinkRoute: typeof AppLinkRoute
  AppRankingRoute: typeof AppRankingRoute
  AppRegrasRoute: typeof AppRegrasRoute
  AppSuporteRoute: typeof AppSuporteRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAjudarRoute: AppAjudarRoute,
  AppContaRoute: AppContaRoute,
  AppConvidarRoute: AppConvidarRoute,
  AppCreditosRoute: AppCreditosRoute,
  AppDenunciarRoute: AppDenunciarRoute,
  AppFilaRoute: AppFilaRoute,
  AppHistoricoRoute: AppHistoricoRoute,
  AppLinkRoute: AppLinkRoute,
  AppRankingRoute: AppRankingRoute,
  AppRegrasRoute: AppRegrasRoute,
  AppSuporteRoute: AppSuporteRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RecuperarRoute: RecuperarRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
